[profile.default]
optimizer = true
optimizer_runs = 20_000
src = "src"
out = "out"
libs = ["lib"]
fs_permissions = [
  { access = "read-write", path = "./" },
  { access = "read-write", path = "/tmp/" },
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
